### ISSUE TITLE
Materialize does not work on modern displays

### ISSUE THREAD

**Issue by jbowler** [BoundingBoxSoftware/Materialize#32]
It bypasses the display scaling, so on any modern display the text is unreadable because it is too small.

**Comment by pwillard** [comment]
I agree.  Unfixable and unreadable on my 4K laptop screen.

**Comment by mhmdnopyadly** [comment]
this new one may work
https://github.com/maikramer/Materialize/releases

**Comment by jbowler** [comment]
Closed: no one is interested in fixing this.
